# Generated by Django 5.0.6 on 2026-04-08 16:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120, verbose_name='Barbershop nomi')),
                ('first_name', models.CharField(max_length=80, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=80, verbose_name='Familiya')),
                ('years_experience', models.PositiveIntegerField(default=1, verbose_name='Staj (yil)')),
                ('specialty', models.CharField(max_length=180, verbose_name="Yo'nalish")),
                ('bio', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('image_url', models.URLField(blank=True, verbose_name='Rasm URL')),
                ('work_start', models.TimeField(default=datetime.time(8, 0), verbose_name='Ish boshlanishi')),
                ('work_end', models.TimeField(default=datetime.time(19, 0), verbose_name='Ish tugashi')),
                ('slot_minutes', models.PositiveIntegerField(default=60, verbose_name='Har slot davomiyligi')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Barber',
                'verbose_name_plural': 'Barberlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, verbose_name='Mijoz ismi')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Telefon raqam')),
                ('start_time', models.DateTimeField(verbose_name='Bron vaqti')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('completed', 'Borib kelindi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.barber')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['start_time', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('barber', 'start_time'), name='unique_barber_slot'),
        ),
    ]
