# Generated by Django 5.0.6 on 2026-04-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_barber_slot',
        ),
    ]
