# Generated by Django 5.0.6 on 2026-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_booking_unique_barber_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
